py_binary(
    name = "notebooks",
    srcs = ["//notebooks"],
    deps = [
        "//learn/daily/d181212_graph_nets_shortest_path:graph_util",
        "//learn/daily/d181212_graph_nets_shortest_path:model",
    ],
)
