cc_test(
    name = "algorithm",
    size = "small",
    srcs = [
        "algorithm.cc",
        "tests.h",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "array",
    size = "small",
    srcs = [
        "array.cc",
        "tests.h",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "forward_list",
    size = "small",
    srcs = [
        "forward_list.cc",
        "tests.h",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "list",
    size = "small",
    srcs = [
        "list.cc",
        "tests.h",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "stack",
    size = "small",
    srcs = [
        "stack.cc",
        "tests.h",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "type_traits",
    size = "small",
    srcs = [
        "tests.h",
        "type_traits.cc",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "unordered_map",
    size = "small",
    srcs = [
        "tests.h",
        "unordered_map.cc",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)

cc_test(
    name = "vector",
    size = "small",
    srcs = [
        "tests.h",
        "vector.cc",
    ],
    copts = [
        "-Ilearn/stl/include",
    ],
    deps = [
        "//labm8/cpp:test",
        "//learn/stl:main",
    ],
)
