# File: //datasets/github/scrape_repos/proto/scrape_repos.proto
# Proto: scrape_repos.LanguageCloneList

# Download Java repos.
# There is *a lot* of Java on GitHub. The problem we have is the 1000 results
# per query limit imposed by GitHub search API.
language {
  language: "java"
  destination_directory: "/var/phd/datasets/github/repos_by_lang/java"
  query {
    string: "language:java sort:stars fork:false"
    max_results: 1000
  }
  query {
    string: "language:java sort:updated fork:false"
    max_results: 1000
  }
  query {
    string: "compute language:java sort:stars fork:false"
    max_results: 1000
  }
  query {
    string: "benchmark language:java sort:stars fork:false"
    max_results: 1000
  }
  importer {
    source_code_pattern: ".*\\.java"
  }
}
