# Protos for managing machines.

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")

py_proto_library(
    name = "data_tiers_pb2_py",
    protos = ["data_tiers.proto"],
    visibility = ["//system/machines:__subpackages__"],
)
