# This package contains OpenCL headers for CLgen.

filegroup(
    name = "opencl",
    srcs = ["opencl.h"],
    visibility = ["//deeplearning/clgen:__subpackages__"],
)

filegroup(
    name = "opencl-shim",
    srcs = ["opencl-shim.h"],
    visibility = ["//deeplearning/clgen:__subpackages__"],
)
