py_binary(
    name = "notebooks",
    srcs = ["//notebooks"],
    deps = [
        "//deeplearning/clgen",
        "//experimental/deeplearning/clgen/backtracking:backtracking_db",
        "//experimental/deeplearning/clgen/closeness_to_grewe_features:grewe_features_db",
        "//research/cummins_2017_cgo:generative_model",
    ],
)
