#!/usr/bin/env bash
set -u

ROOT=$(pwd)

cd opencl

# Run single benchmark by name:
if [[ -n "$1" ]]; then
    cd "$1"
    $SHELL run
    exit $?
fi

# Run all benchmarks:
rm -rf "$ROOT/logs"
mkdir -pv "$ROOT/logs/bad" "$ROOT/logs/good"

for dir in $(ls | sort); do
  echo -n "$(tput bold)rodinia-3.1 $dir$(tput sgr0) ... "
  cd $dir
  $SHELL run &> $ROOT/log.txt
  ret=$?

  if [[ $ret -ne 0 ]]; then
      echo fail
      mv $ROOT/log.txt $ROOT/logs/bad/$dir
  else
    echo ok
    mv $ROOT/log.txt $ROOT/logs/good/$dir
  fi
  cd ..
done
