#!/usr/bin/env bash

ROOT=$(pwd)

cd opencl

# Run single benchmark by name:
if [[ -n "$1" ]]; then
    cd "$1"
    $SHELL run
    exit $?
fi

set -u

# Run all benchmarks:
rm -rf "$ROOT/logs"
mkdir -pv "$ROOT/logs/bad" "$ROOT/logs/good"

for dir in $(ls | sort); do
  echo -n "$(tput bold)rodinia-3.1 $dir$(tput sgr0) ... "
  cd $dir
  $SHELL run
  cd ..
done
