#!/usr/bin/env bash
#
# Count bag-of-words vocabulary size
set -eu

export LC_ALL='C'

tr '[;:,.({})~+-/[]><&!*"#%=?[:space:]]' '\n' < "$1" \
    | grep -v '^$' \
    | sort \
    | uniq -c \
    | sort -n
