#!/usr/bin/env bash

set -eu

usage() {
    echo "Usage: $0 <input1> <input2>"
    echo
    echo "Merge two training datasets."
}

main() {
    if [[ $# -ne 2 ]]; then
        usage >&2
        exit 1
    fi

    local left=$1
    local right=$2

    if [[ $(head -n1 $left) != $(head -n1 $right) ]]; then
        echo "fatal: Header mismatch:" >&2
        echo >&2
        head -n1 $left >&2
        head -n1 $right >&2
        exit 1
    fi

    cat $left
    echo # Line break
    tail -n+2 $right
}

main $@
