#!/usr/bin/env bash

set -eu

usage() {
    echo "Usage: $0 <kernels-dir>"
    echo
    echo "Remove any OpenCL files which do not appear in features.csv"
}

main() {
    if [[ $# -ne 1 ]]; then
        usage >&2
        exit 1
    fi

    local dir=$1
    local features=$dir/features.csv

    if [ ! -f $features ]; then
        echo "fatal: '$features' not found" >&2
        exit 1
    fi

    for path in $(find $dir -name '*.cl'); do
        local f=$(basename $path)

        if ! cut -f1 -d',' < $features | tail -n+2 | grep $f &> /dev/null; then
            rm -v $path
        fi
    done
}

main $@
