#!/usr/bin/env bash
#
# Print the SLOCCOUNT of smith sources.
#
cd ../../
(\
    find docs/wip-smith -name '*.tex'; \
    find src/smith -name '*.py'; \
    find src/smith -name '*.cpp'; \
    find src/smith/bin -type f; \
    find experimental/smith -executable -type f \
) | grep -v '/.eggs/' | grep -v '/build/' | xargs wc -l | sort -n
