load("@requirements//:requirements.bzl", "requirement")

py_test(
    name = 'batch_linear_regression',
    srcs = ['batch_linear_regression.py'],
    size = 'small',
    deps = [
        requirement("absl-py"),
    ]
)
