# Configuration for Better Code analysis.
# See https://bettercodehub.com/docs/configuration-manual
exclude:
  - /datasets/benchmarks/gpgpu/amd-.*
  - /datasets/benchmarks/gpgpu/npb-.*
  - /datasets/benchmarks/gpgpu/nvidia-.*
  - /datasets/benchmarks/gpgpu/parboil-.*
  - /datasets/benchmarks/gpgpu/polybench-.*
  - /datasets/benchmarks/gpgpu/rodinia-.*
  - /datasets/benchmarks/gpgpu/shoc-.*
  - /deeplearning/ncc/.*
  - /gpu/libcecl/libcecl\.[ch]
  - /third_party/.*
# Set component depth to match //<group>/<package>/<component> structure.
component_depth: 3
