# Work in progress on TACO submission.

exports_files(["README.txt"])

# genrule(
#     name = "2016_12_wip_taco",
#     srcs = glob([
#         "*.bst",
#         "*.png",
#         "*.sty",
#         "*.tex",
#         "acmsmall*",
#         "refs.bib",
#     ]),
#     outs = ["2016_12_wip_taco.pdf"],
#     cmd = "$(location //tools:autotex) docs/2016_12_wip_taco/main.tex $@",
#     tools = ["//tools:autotex"],
# )
