# Agumented inst2vec embeddings.

filegroup(
    name = "dictionary",
    srcs = ["inst2vec_augmented_dictionary.pickle"],
    visibility = ["//deeplearning/ml4pl/graphs/unlabelled/cdfg:__subpackages__"],
)

filegroup(
    name = "embeddings",
    srcs = ["inst2vec_augmented_embeddings.pickle"],
    visibility = ["//deeplearning/ml4pl/graphs/unlabelled/cdfg:__subpackages__"],
)
