# File: //deeplearning/deepsmith/proto/generator.proto
# Proto: deepsmith.ClgenGenerator
instance {
  working_dir: "/cache"
  pretrained_model: "/data/model"
  sampler {
    start_text: "kernel void "
    batch_size: 1
    temperature_micros: 800000
    termination_criteria {
      symtok {
        depth_increase_token: "{"
        depth_decrease_token: "}"
      }
    }
    termination_criteria {
      maxlen {
        maximum_tokens_in_sample: 2500
      }
    }
  }
}
testcase_skeleton {
  toolchain: "opencl"
  harness {
    name: "cldrive"
  }
  inputs {
    key: "gsize"
    value: "1,1,1"
  }
  inputs {
    key: "lsize"
    value: "1,1,1"
  }
}
