# Test data.

filegroup(
    name = "legacy_gpgpu_logs",
    testonly = 1,
    srcs = ["legacy_gpgpu_logs.zip"],
    visibility = ["//experimental/deeplearning/clgen/closeness_to_grewe_features/dynamic_features:__subpackages__"],
)
