# Testing code for CLgen.

py_library(
    name = "testlib",
    testonly = True,
    srcs = ["testlib.py"],
    visibility = ["//deeplearning/clgen:__subpackages__"],
    deps = [
        "//deeplearning/clgen:config",
        "//lib/labm8:fs",
        "//lib/labm8:system",
        "//lib/labm8:tar",
    ],
)
