# Protocol buffers for random optimization.

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")

py_proto_library(
    name = "random_opt_py_pb2",
    protos = ["random_opt.proto"],
    visibility = ["//visibility:public"],
    deps = ["//third_party/py/protobuf"],
)
