cc_library(
    name = "ctci",
    hdrs = ["ctci.h"],
    deps = [
        "@gtest//:main",
        "@benchmark//:main",
    ],
)

cc_test(
    name =  "0101-unique-chars-in-string",
    srcs = ["0101-unique-chars-in-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0102-reverse-string",
    srcs = ["0102-reverse-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0103-permutations",
    srcs = ["0103-permutations.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0104-escape-string",
    srcs = ["0104-escape-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0105-string-compression",
    srcs = ["0105-string-compression.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0107-matrix-zero",
    srcs = ["0107-matrix-zero.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0108-string-rotation",
    srcs = ["0108-string-rotation.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0201-list-remove-dups",
    srcs = ["0201-list-remove-dups.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0202-linked-list-k-last",
    srcs = ["0202-linked-list-k-last.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0207-list-palindrone",
    srcs = ["0207-list-palindrone.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0302-stack-min",
    srcs = ["0302-stack-min.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0303-set-of-stacks",
    srcs = ["0303-set-of-stacks.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0305-stack-queue",
    srcs = ["0305-stack-queue.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0402-directed-graph-routefinder",
    srcs = ["0402-directed-graph-routefinder.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0404-binary-tree-list",
    srcs = ["0404-binary-tree-list.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0502-binary-double",
    srcs = ["0502-binary-double.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0505-int-bitdiff",
    srcs = ["0505-int-bitdiff.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "0508-horiz-line",
    srcs = ["0508-horiz-line.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "1101-merge-arrays",
    srcs = ["1101-merge-arrays.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "1102-sort-anagrams",
    srcs = ["1102-sort-anagrams.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "1301-last-k-lines",
    srcs = ["1301-last-k-lines.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "1307-tree-copy",
    srcs = ["1307-tree-copy.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

# FIXME: this is broken
#
# cc_test(
#     name =  "1310-2d-alloc",
#     srcs = ["1310-2d-alloc.cc"],
#     copts = [
#         "-Iexternal/gtest/include",
#         "-Iexternal/benchmark/include",
#     ],
#     deps = [":ctci"],
# )

cc_test(
    name =  "1701-num-swap",
    srcs = ["1701-num-swap.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)

cc_test(
    name =  "1702-tic-tac-toe",
    srcs = ["1702-tic-tac-toe.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
)
