cc_library(
    name = "ctci",
    hdrs = ["ctci.h"],
    deps = [
        "@gtest//:main",
        "@benchmark//:main",
    ],
)

cc_test(
    name =  "0101-unique-chars-in-string-cpp",
    srcs = ["0101-unique-chars-in-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

py_test(
    name =  '0101-unique-chars-in-string-py',
    srcs = ['0101-unique-chars-in-string.py'],
    main =  '0101-unique-chars-in-string.py',
    size = 'small',
)

cc_test(
    name =  "0102-reverse-string-cpp",
    srcs = ["0102-reverse-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0103-permutations-cpp",
    srcs = ["0103-permutations.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

py_test(
    name =  '0103-permutations-py',
    srcs = ['0103-permutations.py'],
    main =  '0103-permutations.py',
    size = 'small',
)

cc_test(
    name =  "0104-escape-string-cpp",
    srcs = ["0104-escape-string.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

py_test(
    name =  '0104-escape-string-py',
    srcs = ['0104-escape-string.py'],
    main =  '0104-escape-string.py',
    size = 'small',
)

cc_test(
    name =  "0105-string-compression-cpp",
    srcs = ["0105-string-compression.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0107-matrix-zero-cpp",
    srcs = ["0107-matrix-zero.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0108-string-rotation-cpp",
    srcs = ["0108-string-rotation.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0201-list-remove-dups-cpp",
    srcs = ["0201-list-remove-dups.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

py_test(
    name =  "0201-list-remove-dups-py",
    srcs = ["0201-list-remove-dups.py"],
    main =  '0201-list-remove-dups.py',
    size = 'small',
)

cc_test(
    name =  "0202-linked-list-k-last-cpp",
    srcs = ["0202-linked-list-k-last.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0207-list-palindrone-cpp",
    srcs = ["0207-list-palindrone.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0302-stack-min-cpp",
    srcs = ["0302-stack-min.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0303-set-of-stacks-cpp",
    srcs = ["0303-set-of-stacks.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0305-stack-queue-cpp",
    srcs = ["0305-stack-queue.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0402-directed-graph-routefinder-cpp",
    srcs = ["0402-directed-graph-routefinder.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0404-binary-tree-list-cpp",
    srcs = ["0404-binary-tree-list.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0502-binary-double-cpp",
    srcs = ["0502-binary-double.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0505-int-bitdiff-cpp",
    srcs = ["0505-int-bitdiff.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "0508-horiz-line-cpp",
    srcs = ["0508-horiz-line.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "1101-merge-arrays-cpp",
    srcs = ["1101-merge-arrays.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "1102-sort-anagrams-cpp",
    srcs = ["1102-sort-anagrams.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "1301-last-k-lines-cpp",
    srcs = ["1301-last-k-lines.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "1307-tree-copy-cpp",
    srcs = ["1307-tree-copy.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

# FIXME: this is broken
#
# cc_test(
#     name =  "1310-2d-alloc-cpp",
#     srcs = ["1310-2d-alloc.cc"],
#     copts = [
#         "-Iexternal/gtest/include",
#         "-Iexternal/benchmark/include",
#     ],
#     deps = [":ctci"],
# )

cc_test(
    name =  "1701-num-swap-cpp",
    srcs = ["1701-num-swap.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)

cc_test(
    name =  "1702-tic-tac-toe-cpp",
    srcs = ["1702-tic-tac-toe.cc"],
    copts = [
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [":ctci"],
    size = 'small',
)
