# Jupyter notebooks server.

py_binary(
    name = "notebooks",
    srcs = ["notebooks.py"],
    deps = [
        "//deeplearning/clgen",
        "//experimental/deeplearning/polyglot:get_instances",
        "//lib/labm8:bazelutil",
        "//lib/labm8:pbutil",
        "//lib/labm8:viz",
    ],
)
