load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["ast.go"],
    importpath = "github.com/ChrisCummins/phd/compilers/toy/ast",
    visibility = ["//visibility:public"],
)
