py_library(
    name = "tests",
    srcs = ["__init__.py"],
)

py_test(
    name = "test_labm8",
    srcs = ["test_labm8.py"],
    deps = [
        ":tests",
        "//labm8",
    ],
)

py_test(
    name = "test_cache",
    srcs = ["test_cache.py"],
    deps = [
        ":tests",
        "//:cache",
        "//:fs",
    ],
)

py_test(
    name = "test_crypto",
    srcs = ["test_crypto.py"],
    deps = [
        ":tests",
        "//:crypto",
    ],
)

py_test(
    name = "test_db",
    srcs = ["test_db.py"],
    deps = [
        ":tests",
        "//:db",
    ],
)

py_test(
    name = "test_dirhashcache",
    srcs = ["test_dirhashcache.py"],
    deps = [
        ":tests",
        "//:dirhashcache",
    ],
)

py_test(
    name = "test_fs",
    srcs = ["test_fs.py"],
    deps = [
        ":tests",
        "//:fs",
    ],
)

py_test(
    name = "test_io",
    srcs = ["test_io.py"],
    deps = [
        ":tests",
        "//:io",
        "//:labm8",
    ],
)

py_test(
    name = "test_jsonutil",
    srcs = ["test_jsonutil.py"],
    deps = [
        ":tests",
        "//:fs",
        "//:jsonutil",
    ],
)

py_test(
    name = "foo",
    srcs = ["foo.py"],
    deps = [
        "//:fs",
        "//:labm8",
    ],
)

py_test(
    name = "test_latex",
    srcs = ["test_latex.py"],
    deps = [
        ":tests",
        "//:latex",
    ],
)

py_test(
    name = "test_lockfile",
    srcs = ["test_lockfile.py"],
    deps = [
        ":tests",
        "//:lockfile",
    ],
)

py_test(
    name = "test_make",
    srcs = ["test_make.py"],
    deps = [
        ":tests",
        "//:fs",
        "//:make",
    ],
)

py_test(
    name = "test_labmath",
    srcs = ["test_labmath.py"],
    deps = [
        ":tests",
        "//:labmath",
    ],
)

py_test(
    name = "test_modules",
    srcs = ["test_modules.py"],
    deps = [
        ":tests",
        "//:modules",
    ],
)

py_test(
    name = "test_prof",
    srcs = ["test_prof.py"],
    deps = [
        ":tests",
        "//:prof",
    ],
)

py_test(
    name = "test_system",
    srcs = ["test_system.py"],
    deps = [
        ":tests",
        "//:fs",
        "//:system",
    ],
)

py_test(
    name = "test_text",
    srcs = ["test_text.py"],
    deps = [
        ":tests",
        "//:text",
    ],
)

py_test(
    name = "test_time",
    srcs = ["test_time.py"],
    deps = [
        ":tests",
        "//:time",
    ],
)

py_test(
    name = "test_labtypes",
    srcs = ["test_labtypes.py"],
    deps = [
        ":tests",
        "//:labtypes",
    ],
)

py_test(
    name = "test_viz",
    srcs = ["test_viz.py"],
    deps = [
        ":tests",
        "//:fs",
        "//:viz",
    ],
)
