py_library(
    name = "tests",
    srcs = ["__init__.py"],
)

py_test(
    name = "test_labm8",
    srcs = ["test_labm8.py"],
    deps = [
        ":tests",
        "//labm8",
    ],
)

py_test(
   name = "test_cache",
   srcs = ["test_cache.py"],
   deps = [":tests", "//labm8:cache"],
)

py_test(
   name = "test_crypto",
   srcs = ["test_crypto.py"],
   deps = [":tests", "//labm8:crypto"],
)

py_test(
   name = "test_db",
   srcs = ["test_db.py"],
   deps = [":tests", "//labm8:db"],
)

py_test(
   name = "test_dirhashcache",
   srcs = ["test_dirhashcache.py"],
   deps = [":tests", "//labm8:dirhashcache"],
)

py_test(
   name = "test_fs",
   srcs = ["test_fs.py"],
   deps = [":tests", "//labm8:fs"],
)

py_test(
   name = "test_io",
   srcs = ["test_io.py"],
   deps = [":tests", "//labm8:io"]
)

py_test(
   name = "test_jsonutil",
   srcs = ["test_jsonutil.py"],
   deps = [":tests", "//labm8:jsonutil"]
)

py_test(
   name = "test_latex",
   srcs = ["test_latex.py"],
   deps = [":tests", "//labm8:latex"]
)

py_test(
   name = "test_lockfile",
   srcs = ["test_lockfile.py"],
   deps = [":tests", "//labm8:lockfile"]
)

py_test(
   name = "test_make",
   srcs = ["test_make.py"],
   deps = [":tests", "//labm8:make"]
)

py_test(
   name = "test_math",
   srcs = ["test_math.py"],
   deps = [":tests", "//labm8:math"]
)

py_test(
   name = "test_modules",
   srcs = ["test_modules.py"],
   deps = [":tests", "//labm8:modules"]
)

py_test(
   name = "test_prof",
   srcs = ["test_prof.py"],
   deps = [":tests", "//labm8:prof"]
)

py_test(
   name = "test_system",
   srcs = ["test_system.py"],
   deps = [":tests", "//labm8:system"]
)

py_test(
   name = "test_tar",
   srcs = ["test_tar.py"],
   deps = [":tests", "//labm8:tar"]
)

py_test(
   name = "test_text",
   srcs = ["test_text.py"],
   deps = [":tests", "//labm8:text"]
)

py_test(
   name = "test_time",
   srcs = ["test_time.py"],
   deps = [":tests", "//labm8:time"]
)

py_test(
   name = "test_types",
   srcs = ["test_types.py"],
   deps = [":tests", "//labm8:types"]
)

py_test(
   name = "test_viz",
   srcs = ["test_viz.py"],
   deps = [":tests", "//labm8:viz"]
)
