
build/3.8.0/bin/clang:
	wget http://releases.llvm.org/3.8.0/clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
	tar xf clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz
	mv clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04 build/3.8.0
	rm clang+llvm-3.8.0-x86_64-linux-gnu-ubuntu-16.04.tar.xz

build/3.7.0/bin/clang:
	wget http://releases.llvm.org/3.7.0/clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
	tar xf clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
	mv clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04 build/3.7.0
	rm clang+llvm-3.7.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz

build/3.6.1/bin/clang:
	wget http://releases.llvm.org/3.6.1/clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-15.04.tar.xz
	tar xf clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-15.04.tar.xz
	mv clang+llvm-3.6.1-x86_64-linux-gnu build/3.6.1
	rm clang+llvm-3.6.1-x86_64-linux-gnu-ubuntu-15.04.tar.xz

build/3.6.0/bin/clang:
	wget http://releases.llvm.org/3.6.0/clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
	tar xf clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
	mv clang+llvm-3.6.0-x86_64-linux-gnu build/3.6.0
	rm clang+llvm-3.6.0-x86_64-linux-gnu-ubuntu-14.04.tar.xz
