comment: "Source files for my talk at ISSTA\'18."
file {
  comment: "The keynote slides, with animations inlined."
  relative_path: "ISSTA (no animations).key"
}
file {
  comment: "The keynote slides."
  relative_path: "ISSTA.key"
}
file {
  comment: "A screen grab of the opencl_fuzz demo."
  relative_path: "assets/opencl_fuzz.gif"
}
unix_epoch_ms_packaged: 1531751239570
checksum_hash: SHA256
checksum: "9e6a0f44a04f4bfde38d1b386eb3e9305e730f92f3f533cd12c69057d2aff1b9"
