#!/usr/bin/env bash
set -eu


cd samples/opencl/cl/1.x

# Clean up
set +e
make clean &>/dev/null
find . -iwholename '*cmake*' -not -name CMakeLists.txt -delete &>/dev/null
set -e

cmake . >/dev/null
make -j $(nproc)
