#!/usr/bin/env bash
#
# Summarize npb benchmark logs in ../data/npb/results/.
#
# Usage: ./summarize <data-dir>
#
set -eu

usage() {
    echo "$0 <data-path>"
    echo
    echo "     Summarize and plot NPB benchmark results."
}

get_roots() {
    local path="$1"
    ls $path/*.cpu.out | sed 's/\.cpu\.out$//' | xargs -L 1 basename
}

extract_runtimes() {
    local path="$1"

    local root=$(basename "$path" | sed 's/\.out$//')
    local benchmark=$(echo $root | cut -d '.' -f 1)
    local dataset=$(echo $root | cut -d '.' -f 2)
    local device=$(echo $root | cut -d '.' -f 3 | tr '[:lower:]' '[:upper:]')
    local run=$(basename $(dirname "$path"))

    # output format: benchmark,dataset,device,run,runtime
    grep '\[CEC\] clEnqueue' "$path" \
        | awk '{print $5}' | awk '{print "'$benchmark,$dataset,$device,$run,'" $0}'
}

extract_wgsizes() {
    local path="$1"

    local root=$(echo "$(basename $path)" | sed 's/\.out$//')
    local benchmark=$(echo $root | cut -d '.' -f 1)
    local dataset=$(echo $root | cut -d '.' -f 2)
    local device=$(echo $root | cut -d '.' -f 3 | tr '[:lower:]' '[:upper:]')

    # output format: benchmark,dataset,device,wgsize
    grep '\[CEC\] clEnqueueNDRangeKernel ' "$path" \
        | awk '{print $4}' | awk '{print "'$benchmark,$dataset,$device,'" $0}'
}

extract_transfers() {
    local path="$1"

    local root=$(echo "$(basename $path)" | sed 's/\.out$//')
    local benchmark=$(echo $root | cut -d '.' -f 1)
    local dataset=$(echo $root | cut -d '.' -f 2)
    local device=$(echo $root | cut -d '.' -f 3 | tr '[:lower:]' '[:upper:]')

    # output format: benchmark,dataset,device,size
    grep '\[CEC\] clEnqueue[RW]' "$path" \
        | awk '{print $4}' | awk '{print "'$benchmark,$dataset,$device,'" $0}'
}

extract_kernels() {
    local path="$1"

    local root=$(echo "$(basename $path)" | sed 's/\.out$//')
    local benchmark=$(echo $root | cut -d '.' -f 1)
    local dataset=$(echo $root | cut -d '.' -f 2)

    # output format: benchmark,dataset,kernel
    grep '\[CEC\] clCreateKernel ' "$path" \
        | awk '{print $3}' | awk '{print "'$benchmark,'" $0}'
}

make_csvs() {
    local data_path="$1"
    local runtimes_csv_path="$2"
    local wgsizes_csv_path="$3"
    local transfers_csv_path="$4"
    local kernels_csv_path="$5"

    local rundirs=($(find "$data_path" -maxdepth 1 -regex '.*[0-9]+' ! -path "$data_path" -type d | sort))
    local nruns=$(echo ${#rundirs[@]})
    local dsize=$(du -h -s "$data_path" | awk '{print $1}')

    echo "summarizing $dsize of data from $nruns runs ..."

    roots=($(get_roots "${rundirs[0]}"))

    # CSV HEADERS
    echo "benchmark,dataset,device,run,runtime" > "$runtimes_csv_path"
    echo "benchmark,dataset,device,wgsize" > "$wgsizes_csv_path"
    echo "benchmark,dataset,device,size" > "$transfers_csv_path"
    rm -f "$kernels_csv_path"

    for rundir in ${rundirs[@]}; do
        for root in ${roots[@]}; do
            cpu_path="$rundir/$root.cpu.out"
            gpu_path="$rundir/$root.gpu.out"

            extract_runtimes "$cpu_path" >> "$runtimes_csv_path"
            extract_runtimes "$gpu_path" >> "$runtimes_csv_path"

            extract_wgsizes "$cpu_path" >> "$wgsizes_csv_path"
            extract_wgsizes "$gpu_path" >> "$wgsizes_csv_path"

            extract_transfers "$cpu_path" >> "$transfers_csv_path"
            extract_transfers "$gpu_path" >> "$transfers_csv_path"

            extract_kernels "$cpu_path" >> "$kernels_csv_path"
        done
    done

    # Make list of kernels (across all benchmarks/datasets)
    sort -u < "$kernels_csv_path" > /tmp/kernels
    echo "benchmark,kernel" > "$kernels_csv_path"
    cat /tmp/kernels >> "$kernels_csv_path"
    rm -f /tmp/kernels
}

open_stuff() {
    local args="$@"

    if [[ "$(uname)" == "Darwin" ]]; then
        open $args
    else
        xdg-open $args
    fi
}

main() {
    if [[ $# -ne 1 ]] || [[ ! -d "$1" ]]; then
        usage >&2
        exit 1
    fi

    local data_path="$1"
    local results_path="$1/results"
    local runtimes_csv_path="$results_path/runtimes.csv"
    local wgsizes_csv_path="$results_path/wgsizes.csv"
    local transfers_csv_path="$results_path/transfers.csv"
    local kernels_csv_path="$results_path/kernels.csv"
    local db_path="$results_path/data.db"

    make_csvs "$results_path" \
              "$runtimes_csv_path" \
              "$wgsizes_csv_path" \
              "$transfers_csv_path" \
              "$kernels_csv_path"
    ./analyze "$data_path"
    open_stuff "$results_path/img"
}
main $@
