# Experiments while porting CLgen from Tensorflow to Keras models.

py_test(
    name = "benchmark_module_import",
    srcs = ["benchmark_module_import.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)

py_test(
    name = "benchmark_model_init",
    srcs = ["benchmark_model_init.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)

py_test(
    name = "benchmark_string_concatenation",
    srcs = ["benchmark_string_concatenation.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)

py_test(
    name = "log_to_file",
    srcs = ["log_to_file.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)
