# Experiments while porting CLgen from Tensorflow to Keras models.

py_test(
    name = "profile_module_import",
    srcs = ["profile_module_import.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)

py_test(
    name = "profile_model_init",
    srcs = ["profile_model_init.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
)
