# Internal implementation libraries for labm8.

py_library(
    name = "flags_parsers",
    srcs = ["flags_parsers.py"],
    visibility = ["//labm8:__subpackages__"],
    deps = [
        "//labm8:sqlutil",
        "//third_party/py/absl",
    ],
)

py_library(
    name = "logging",
    srcs = ["logging.py"],
    visibility = ["//labm8:__subpackages__"],
    deps = [
        "//third_party/py/absl",
    ],
)
