py_binary(
    name = "train_ggnn",
    srcs = ["train_ggnn.py"],
    deps = [
        "//labm8/py:app",
        "//labm8/py:ppar",
        "//labm8/py:progress",
        "//programl/graph/py:graph_tuple_builder",
        "//programl/ml/batch:rolling_results",
        "//programl/ml/epoch",
        "//programl/ml/model/ggnn",
        "//programl/proto:epoch_py",
        "//programl/proto:program_graph_features_py",
        "//programl/proto:program_graph_py",
    ],
)
