# Smoke test of CLgen docker image.

sh_test(
    name = "smoke_test",
    srcs = ["smoke_test.sh"],
    data = [
        "//deeplearning/clgen/docker:clgen.tar",
        "//deeplearning/clgen/tests/data/tiny",
    ],
)
