# Protocol buffers used by //util/photolib.

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")

py_proto_library(
    name = "photolint",
    protos = ["photolint.proto"],
    visibility = ["//util/photolib:__subpackages__"],
)
