py_library(
    name = "lexer_smoke_test",
    testonly = 1,
    srcs = ["lexer_smoke_test.py"],
    data = [
        "//compilers/toy:test_data",
        "//compilers/toy/util/lex",
    ],
    deps = [
        "//compilers/toy/tests:smoke_test_flags",
        "//labm8/py:app",
        "//labm8/py:bazelutil",
        "//labm8/py:fs",
        "//labm8/py:test",
    ],
)

py_test(
    name = "lexer_smoke_test_stage1",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "1",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage2",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "2",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage3",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "3",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage4",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "4",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage5",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "5",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage6",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "6",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage7",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "7",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage8",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "8",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage9",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "9",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)

py_test(
    name = "lexer_smoke_test_stage10",
    srcs = ["lexer_smoke_test.py"],
    args = [
        "--stage",
        "10",
    ],
    main = "lexer_smoke_test.py",
    deps = [":lexer_smoke_test"],
)
