# Private helper files for //phd library.

cc_library(
    name = "macros_impl",
    hdrs = ["macros_impl.h"],
    visibility = ["//phd:__pkg__"],
    deps = [
        "@com_google_absl//absl/strings:str_format",
        "@com_google_absl//absl/time",
    ],
)
