# FreeFocus scripts.

py_binary(
    name = "github_to_proto",
    srcs = ["github_to_proto.py"],
    deps = ["//util/freefocus:freefocus_pb_py"],
)

py_binary(
    name = "github_to_sql",
    srcs = ["github_to_sql.py"],
    deps = ["//util/freefocus:sql"],
)

py_binary(
    name = "omnifocus_to_sql",
    srcs = ["omnifocus_to_sql.py"],
    deps = ["//util/freefocus:sql"],
)

py_binary(
    name = "proto_to_dot",
    srcs = ["proto_to_dot.py"],
    deps = ["//util/freefocus:freefocus_pb_py"],
)

py_binary(
    name = "sql_to_dot",
    srcs = ["sql_to_dot.py"],
    deps = ["//util/freefocus:sql"],
)

py_binary(
    name = "sql_to_html_timeline",
    srcs = ["sql_to_html_timeline.py"],
    deps = ["//util/freefocus:sql"],
)
