#!/usr/bin/env bash

set -eu

rm -rf results
mkdir -pv results

./compile &>/dev/null

for i in $(seq 1 30); do
    echo "run $i ..."
    cd bin
    rm -rf log
    mkdir -p log
    ./run_ocl_cpu.sh &> log/cpu.sh
    ./run_ocl_gpu.sh &> log/gpu.sh
    cd ..
    mv bin/log results/$i
done
