# Learning PostgreSQL

cc_test(
    name = "hello_world",
    srcs = ["hello_world.cc"],
    deps = [
        "//labm8/cpp:logging",
        "//labm8/cpp:status",
        "//labm8/cpp:statusor",
        "//third_party/libpqxx",
    ],
)
