#!/usr/bin/env bash
#
# Run clgen-verify on directory and log results
#
# Usage:
#
#     ./automate cpu --cpu
#     ./automate gpu
#

TIMEOUT=${TIMEOUT:-15}

DEVNAME=$1
DEVARG=$2

INDIR=~/data/synthetic-2017-02-01
OUTDIR=~/data/verify

while true; do
    timeout --signal=9 $TIMEOUT \
        clgen-verify $OUTDIR/$DEVNAME.db $INDIR $DEVARG 2>/dev/null \
        | tee -a $OUTDIR/$DEVNAME.log
    echo | tee -a $OUTDIR/$DEVNAME.log
done
