# Experiments in machine learning for compiler test case analysis.

py_binary(
     name = "export_discriminator_training_set",
     srcs = ["export_discriminator_training_set.py"],
     deps = ["//experimental/fish/proto:fish_py_pb2"],
)

py_binary(
     name = "train_discriminator",
     srcs = ["train_discriminator.py"],
     deps = ["//experimental/fish/proto:fish_py_pb2"],
)
