py_binary(
    name = "jacobi_demo",
    srcs = ["jacobi_demo.py"],
    deps = [
        "//datasets/benchmarks/jacobi_opencl",
        "//labm8/py:app",
        "//labm8/py:humanize",
        "//labm8/py:jsonutil",
        "//labm8/py:prof",
    ],
)
