py_test(
    name = "ggnn_node_classifier_smoke_test",
    size = "enormous",
    srcs = ["ggnn_node_classifier_smoke_test.py"],
    deps = [
        "//deeplearning/ml4pl/graphs:graph_database",
        "//deeplearning/ml4pl/models:classifier_smoke_tester",
        "//deeplearning/ml4pl/models/ggnn:ggnn_node_classifier",
        "//labm8:app",
        "//third_party/py/numpy",
    ],
)
