# Smoke test for report generator.

sh_test(
    name = "smoke_test",
    srcs = ["smoke_test.sh"],
    data = [
        "//tools/continuous_integration/buildbot/report_generator",
        "//tools/continuous_integration/buildbot/report_generator/test/data/testlogs",
    ],
)
