# Scripts for training models.

sh_binary(
    name = "devmap_zero_r",
    srcs = ["devmap_zero_r.sh"],
    data = ["//deeplearning/ml4pl/models/zero_r"],
)

sh_binary(
    name = "devmap_ggnn",
    srcs = ["devmap_ggnn.sh"],
    data = ["//deeplearning/ml4pl/models/ggnn"],
)
