# Tests for toy compiler.

py_library(
    name = "smoke_test_flags",
    testonly = 1,
    srcs = ["smoke_test_flags.py"],
    visibility = ["//compilers/toy/tests:__subpackages__"],
    deps = ["//labm8:app"],
)
