py_binary(
    name = "benchmark_clgen",
    srcs = ["benchmark_clgen.py"],
    deps = [
        "//deeplearning/clgen",
        "//deeplearning/clgen:sample_observers",
        "//labm8/py:app",
        "//labm8/py:pbutil",
        "//labm8/py:prof",
    ],
)
