# Learning Python.

py_test(
    name = "ascii_chart",
    srcs = ["ascii_chart.py"],
    default_python_version = "PY3",
    srcs_version = "PY3",
    deps = [
        "//third_party/py/absl",
        "//third_party/py/ascii_art",
        "//third_party/py/pytest",
    ],
)

py_binary(
    name = "debugger",
    srcs = ["debugger.py"],
    deps = [
        "//third_party/py/absl",
        "//third_party/py/ipdb",
    ]
)
