cc_binary(
    name = "010-summation-of-primes",
    srcs = ["010-summation-of-primes.c"],
)

cc_binary(
    name = "011-largest-product-in-a-grid",
    srcs = ["011-largest-product-in-a-grid.c"],
)

cc_binary(
    name = "012-triangle-number",
    srcs = ["012-triangle-number.cc"],
)

sh_binary(
    name = "013-large-sum",
    srcs = ["013-large-sum.py"],
)

sh_binary(
    name = "015-lattice-paths-py",
    srcs = ["015-lattice-paths.py"],
)

cc_binary(
    name = "015-lattice-paths-cpp",
    srcs = ["015-lattice-paths.cc"],
)

sh_binary(
    name = "016-power-digits-sum",
    srcs = ["016-power-digits-sum.py"],
)

sh_binary(
    name = "017-number-letter-counts",
    srcs = ["017-number-letter-counts.py"],
)

cc_test(
    name = "018_maximum_path_sum",
    srcs = ["018_maximum_path_sum.cc"],
    deps = [
        "//labm8/cpp:logging",
    ],
)

cc_test(
    name = "019_counting_sundays",
    srcs = ["019_counting_sundays.cc"],
)
