cc_binary(
    name =  "010-summation-of-primes",
    srcs = ["010-summation-of-primes.c"],
)

cc_binary(
    name =  "011-largest-product-in-a-grid",
    srcs = ["011-largest-product-in-a-grid.c"],
)

sh_binary(
    name =  "013-large-sum",
    srcs = ["013-large-sum.py"],
)
