cc_library(
    name = "container",
    hdrs = ["container.hpp"],
)

#cc_test(
#    name = "main",
#    size = "small",
#    srcs = [
#        "main.cc",
#    ],
#    deps = [
#        ":container",
#        "//labm8/cpp:test",
#    ],
#)
