cc_library(
    name = "container",
    hdrs = ["container.hpp"],
)

# TODO(cec): This target doesn't build with GCC 5.5.0 toolchain on Linux, but
# does using clang 6.0.
# cc_test(
#     name = "main",
#     size = "small",
#     srcs = [
#         "main.cc",
#     ],
#     copts = [
#         "-Ilib/phd/include",
#     ],
#     deps = [
#         ":container",
#         "//lib/phd:main"
#     ],
# )
