#!/usr/bin/env bash

#
# Drive OpenCL files in a directory.
#
set -e

# TIMEOUT is the timeout threshold in seconds.
TIMEOUT=${TIMEOUT:-180}

# STRICT enables cldrive dynamic checker if 1.
STRICT=${STRICT:-0}

set -u

usage() {
    echo "Usage: $0 <cpu|gpu> <dsize> <opencl-dir>"
}

drive_file() {
    local in_path=$1
    local devargs=$2
    local dsize=$3

    if [[ $STRICT == 1 ]]; then
        devargs="$devargs --strict"
    fi

    DSIZE=$dsize timeout --signal=9 $TIMEOUT cldrive -f $devargs $in_path
    set -e
}

main() {
    if [[ $# -ne 3 ]]; then
        usage >&2
        exit 1
    fi

    local devtype=$1
    local dsize=$2
    local in_dir=$3

    if [[ $devtype != "cpu" ]] && [[ $devtype != "gpu" ]]; then
        usage >&2
        exit 1
    fi

    for f in $(find $in_dir -name '*.cl' -type f); do
        drive_file $f --$devtype $dsize
    done
}

main $@
