py_binary(
    name = "jacobi_demo",
    srcs = ["jacobi_demo.py"],
    deps = [
        "//datasets/benchmarks/jacobi_opencl",
        "//labm8:app",
        "//labm8:humanize",
        "//labm8:jsonutil",
        "//labm8:prof",
    ],
)
