# Tests for formatters.

py_test(
    name = "bazel_test",
    srcs = ["bazel_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:bazel",
    ],
)

py_test(
    name = "cxx_test",
    srcs = ["cxx_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:cxx",
    ],
)

py_test(
    name = "go_test",
    srcs = ["go_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:go",
    ],
)

py_test(
    name = "json_test",
    srcs = ["json_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:json",
    ],
)

py_test(
    name = "protobuf_test",
    srcs = ["protobuf_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:protobuf",
    ],
)

py_test(
    name = "python_test",
    srcs = ["python_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:python",
    ],
)

py_test(
    name = "shell_test",
    srcs = ["shell_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:shell",
    ],
)

py_test(
    name = "sql_test",
    srcs = ["sql_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:sql",
    ],
)

py_test(
    name = "text_test",
    srcs = ["text_test.py"],
    deps = [
        "//labm8/py:test",
        "//tools/format/formatters:text",
    ],
)
