#!/usr/bin/env bash
#
# Drive OpenCL files in a directory.
#
set -eu

usage() {
    echo "Usage: $0 <cpu|gpu> <dsize> <opencl-dir>"
}

drive_file() {
    local in_path=$1
    local devargs=$2
    local dsize=$3

    DSIZE=$dsize timeout 10 cldrive --strict -f $devargs $in_path
    set -e
}

main() {
    if [[ $# -ne 3 ]]; then
        usage >&2
        exit 1
    fi

    local devtype=$1
    local dsize=$2
    local in_dir=$3

    if [[ $devtype != "cpu" ]] && [[ $devtype != "gpu" ]]; then
        usage >&2
        exit 1
    fi

    for f in $(find $in_dir -name '*.cl' -type f); do
        drive_file $f --$devtype $dsize
    done
}
main $@
