#!/usr/bin/env bash
#
# Rebuild training data. Run pull-results beforehand.
#
set -eux

wait_for_jobs() {
    for job in $(jobs -p); do
        wait $job;
    done
}

main() {
    # Make static kernel features.
    cd data/synthetic/kernels
    ls | grep '.cl' | xargs -L 1000 smith-features > features.csv
    cd ../../../

    # Make kernels tarball.
    cd data/synthetic/
    local archive=$(date +"kernels-%y.%m.%d-%H.%M.tar.bz2")
    tar -cjf $archive kernels
    cd ../../

    # Prune kernel files (optional).
    cd ../
    ./prune-kernels driver/data/synthetic/kernels
    cd driver

    # Make error files.
    ./mkerros intel data/synthetic/
    ./mkerros amd data/synthetic/
    ./mkerros nvidia data/synthetic/

    # Make training data files (one for each platform and combined).
    ./mktraining data/synthetic/kernels \
                 data/synthetic/intel.csv \
                 data/synthetic/amd.csv \
                 > data/synthetic/platform-a.csv

    ./mktraining data/synthetic/kernels \
                 data/synthetic/intel.csv \
                 data/synthetic/nvidia.csv \
                 > data/synthetic/platform-b.csv

    cd ../
    ./merge-training-data driver/data/synthetic/platform-a.csv \
                          driver/data/synthetic/platform-b.csv \
                          > driver/data/synthetic/training-combined.csv
    cd driver

    # Extract kernels.
    cd ../
    ./extract-synthetic-kernels driver/data/synthetic/platform-a.csv \
                                driver/data/synthetic/kernels \
                                > driver/data/synthetic/platform-a.cl &
    ./extract-synthetic-kernels driver/data/synthetic/platform-b.csv \
                                driver/data/synthetic/kernels \
                                > driver/data/synthetic/platform-b.cl &
    ./extract-synthetic-kernels driver/data/synthetic/training-combined.csv \
                                driver/data/synthetic/kernels \
                                > driver/data/synthetic/training-combined.cl &
    wait_for_jobs

    cd driver
}
main $@
