# DEPRECATED.
#py_library(
#    name = "control_flow_graph_generator",
#    srcs = ["control_flow_graph_generator.py"],
#    visibility = ["//visibility:public"],
#    deps = [
#        ":control_flow_graph",
#        "//labm8:app",
#        "//third_party/py/networkx",
#        "//third_party/py/numpy",
#    ],
#)
#
#py_test(
#    name = "control_flow_graph_generator_test",
#    timeout = "long",
#    srcs = ["control_flow_graph_generator_test.py"],
#    deps = [
#        ":control_flow_graph_generator",
#        "//labm8:app",
#        "//labm8:test",
#        "//third_party/py/networkx",
#    ],
#)
#
#py_binary(
#    name = "eval_model",
#    srcs = ["eval_model.py"],
#    deps = [
#        ":ml4pl_pb_py",
#        "//deeplearning/clgen:telemetry",
#        "//deeplearning/clgen/corpuses:atomizers",
#        "//labm8:app",
#        "//labm8:humanize",
#        "//labm8:pbutil",
#        "//third_party/py/keras",
#        "//third_party/py/numpy",
#    ],
#)
