# Git utilities.

py_library(
    name = "git_clone",
    srcs = ["git_clone.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//labm8/py:app",
    ],
)

sh_binary(
    name = "repo_stats",
    srcs = ["repo_stats.sh"],
)
