# Git utilities.

sh_binary(
    name = "repo_stats",
    srcs = ["repo_stats.sh"],
)

filegroup(
    name = "hooks",
    srcs = [
        "post_commit.py",
        "post_rebase.py",
        "pre_commit.py",
        "pre_push.py",
    ],
)
