language {
  language: "haskell"
  query {
    string: "language:haskell sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/haskell"
  importer {
    source_code_pattern: ".*\\.hs"
  }
}
