# File: //datasets/github/scrape_repos/proto/scrape_repos.proto
# Proto: scrape_repos.LanguageCloneList

# Clone lists languages I haven't yet started on.

# Download GLSL source code.
language {
  language: "glsl"
  query {
    string: "language:glsl sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/glsl"
  importer {
    source_code_pattern: ".*\\.glsl"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.frag"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.vert"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.tesc"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.tese"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.geom"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
  importer {
    source_code_pattern: ".*\\.comp"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
}

# Download source code for solidity, the language of the Ethereum blockchain.
# As with OpenCL, Solidity is not treated as a first-class language and we
# cannot filter by it. Our hit ratio is likely to be low.
language {
  language: "solidity"
  query {
    string: "solidity sort:stars fork:false"
    max_results: 1000
  }
  query {
    string: "ethereum sort:stars fork:false"
    max_results: 1000
  }
  query {
    string: "solc sort:stars fork:false"
    max_results: 1000
  }
  importer {
    source_code_pattern: ".*\\.sol"
  }
}

language {
  language: "javascript"
  query {
    string: "language:javascript sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/javascript"
}

language {
  language: "haskell"
  query {
    string: "language:haskell sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/haskell"
}
language {
  language: "go"
  query {
    string: "language:go sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/go"
}

language {
  language: "php"
  query {
    string: "language:php sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/php"
}
language {
  language: "python"
  query {
    string: "language:python sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/python"
}
language {
  language: "rust"
  query {
    string: "language:rust sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/rust"
}
language {
  language: "elixir"
  query {
    string: "language:elixir sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/elixir"
}
language {
  language: "objective-c"
  query {
    string: "language:objective-c sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/objective_c"
}
language {
  language: "ocaml"
  query {
    string: "language:ocaml sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/ocaml"
}
language {
  language: "ruby"
  query {
    string: "language:ruby sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/ruby"
}
language {
  language: "perl"
  query {
    string: "language:perl sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/perl"
}
language {
  language: "scala"
  query {
    string: "language:scala sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/scala"
}
language {
  language: "lua"
  query {
    string: "language:lua sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/lua"
}
language {
  language: "clojure"
  query {
    string: "language:clojure sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/clojure"
}
