# File: //datasets/github/scrape_repos/proto/scrape_repos.proto
# Proto: scrape_repos.LanguageCloneList
language {
  language: "swift"
  query {
    string: "language:swift sort:stars fork:false"
    max_results: 1000
  }
  destination_directory: "/var/phd/datasets/github/repos_by_lang/swift"
  importer {
    source_code_pattern: ".*\\.swift"
    preprocessor: "datasets.github.scrape_repos.preprocessors.inliners:CxxHeadersDiscardUnknown"
  }
}
