# Tools for managing machines.

py_binary(
    name = "data_tiers",
    srcs = ["data_tiers.py"],
    deps = [
        "//lib/labm8:pbutil",
        "//system/machines/ryangosling/proto:ryangosling_pb2_py",
    ],
)
