# File: //deeplearning/clgen/proto/corpus.proto
# Proto: clgen.Corpus
local_directory: "/mnt/cc/data/datasets/github/corpuses/c"
contentfile_separator: "\n\n"
preprocessor: "deeplearning.clgen.preprocessors.cxx:ClangPreprocess"
preprocessor: "deeplearning.clgen.preprocessors.cxx:Compile"
preprocessor: "deeplearning.clgen.preprocessors.cxx:NormalizeIdentifiers"
preprocessor: "deeplearning.clgen.preprocessors.common:StripDuplicateEmptyLines"
preprocessor: "deeplearning.clgen.preprocessors.common:StripTrailingWhitespace"
preprocessor: "deeplearning.clgen.preprocessors.cxx:ClangFormat"
preprocessor: "deeplearning.clgen.preprocessors.common:MinimumLineCount3"
preprocessor: "deeplearning.clgen.preprocessors.cxx:Compile"
# The set of C99 and C++ keywords.
greedy_multichar_atomizer {
  tokens: "alignas"
  tokens: "alignof"
  tokens: "and"
  tokens: "and_eq"
  tokens: "asm"
  tokens: "atomic_cancel"
  tokens: "atomic_commit"
  tokens: "atomic_noexcept"
  tokens: "auto"
  tokens: "bitand"
  tokens: "bitor"
  tokens: "bool"
  tokens: "break"
  tokens: "case"
  tokens: "catch"
  tokens: "char"
  tokens: "char16_t"
  tokens: "char32_t"
  tokens: "class"
  tokens: "co_await"
  tokens: "co_return"
  tokens: "co_yield"
  tokens: "compl"
  tokens: "concept"
  tokens: "const"
  tokens: "const_cast"
  tokens: "constexpr"
  tokens: "continue"
  tokens: "decltype"
  tokens: "default"
  tokens: "delete"
  tokens: "do"
  tokens: "double"
  tokens: "dynamic_cast"
  tokens: "else"
  tokens: "enum"
  tokens: "explicit"
  tokens: "export"
  tokens: "extern"
  tokens: "false"
  tokens: "float"
  tokens: "for"
  tokens: "friend"
  tokens: "goto"
  tokens: "if"
  tokens: "import"
  tokens: "inline"
  tokens: "int"
  tokens: "long"
  tokens: "module"
  tokens: "mutable"
  tokens: "namespace"
  tokens: "new"
  tokens: "noexcept"
  tokens: "not"
  tokens: "not_eq"
  tokens: "nullptr"
  tokens: "operator"
  tokens: "or"
  tokens: "or_eq"
  tokens: "private"
  tokens: "protected"
  tokens: "public"
  tokens: "register"
  tokens: "reinterpret_cast"
  tokens: "requires"
  tokens: "return"
  tokens: "short"
  tokens: "signed"
  tokens: "sizeof"
  tokens: "static"
  tokens: "static_assert"
  tokens: "static_cast"
  tokens: "struct"
  tokens: "switch"
  tokens: "synchronized"
  tokens: "template"
  tokens: "this"
  tokens: "thread_local"
  tokens: "throw"
  tokens: "true"
  tokens: "try"
  tokens: "typedef"
  tokens: "typeid"
  tokens: "typename"
  tokens: "union"
  tokens: "unsigned"
  tokens: "using"
  tokens: "virtual"
  tokens: "void"
  tokens: "volatile"
  tokens: "wchar_t"
  tokens: "while"
  tokens: "xor"
  tokens: "xor_eq"
}
