# File: //deeplearning/clgen/proto/corpus.proto
# Proto: clgen.Corpus
local_directory: "/mnt/cc/data/datasets/github/corpuses/java"
ascii_character_atomizer: true
contentfile_separator: "\n\n"
# For now we've not going to worry about even testing to see if the Java
# files are statically compilable, since I don't want to exclude files with
# user package imports.
# preprocessor: "deeplearning.clgen.preprocessors.java:Compile"
preprocessor: "deeplearning.clgen.preprocessors.cxx:StripComments"
preprocessor: "deeplearning.clgen.preprocessors.java:ClangFormat"
preprocessor: "deeplearning.clgen.preprocessors.common:StripDuplicateEmptyLines"
preprocessor: "deeplearning.clgen.preprocessors.common:StripTrailingWhitespace"

