# Zero-R models.

py_binary(
    name = "zero_r",
    srcs = ["zero_r.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//deeplearning/ml4pl/graphs/labelled/graph_tuple:graph_batcher",
        "//deeplearning/ml4pl/models:classifier_base",
        "//deeplearning/ml4pl/models:log_database",
        "//labm8:app",
        "//third_party/py/numpy",
    ],
)
