#!/usr/bin/env bash
set -u


ROOT=$(pwd)

rm -rf logs
mkdir -p logs/bad logs/good

cd OpenCL/bin/linux/release

for f in $(find . -type f -executable | sort); do
    echo -n "$(tput bold)nvidia-4.2 $f$(tput sgr0) ... "
    runcecl $f > $ROOT/log.txt
    ret=$?

    if [[ $ret -ne 0 ]]; then
      echo fail
      mv $ROOT/log.txt $ROOT/logs/bad/$(basename $f)
    else
      echo ok
      mv $ROOT/log.txt $ROOT/logs/good/$(basename $f)
    fi
done
