#!/usr/bin/env bash
set -eu

benchmarks=(
    2DCONV
    2MM
    3DCONV
    3MM
    ATAX
    BICG
    CORR
    COVAR
    FDTD-2D # BAD
    GEMM
    GESUMMV
    GRAMSCHM
    MVT
    SYR2K
    SYRK
)

cd OpenCL

for benchmark in ${benchmarks[@]}; do
    echo "$(tput bold)polyben-gpu-1.0 $benchmark$(tput sgr0) ..."
    cd $benchmark
    $(find . -executable -type f)
    cd ..
done
