py_library(
    name = "ast_smoke_test",
    testonly = 1,
    srcs = ["ast_smoke_test.py"],
    data = [
        "//compilers/toy:test_data",
        "//compilers/toy/util/print_ast",
    ],
    deps = [
        "//compilers/toy/tests:smoke_test_flags",
        "//labm8:app",
        "//labm8:bazelutil",
        "//labm8:fs",
        "//labm8:test",
    ],
)

py_test(
    name = "ast_smoke_test_stage1",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "1",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage2",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "2",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage3",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "3",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage4",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "4",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage5",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "5",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage6",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "6",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage7",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "7",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage8",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "8",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage9",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "9",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)

py_test(
    name = "ast_smoke_test_stage10",
    srcs = ["ast_smoke_test.py"],
    args = [
        "--stage",
        "10",
    ],
    main = "ast_smoke_test.py",
    deps = [":ast_smoke_test"],
)
