# FreeFocus REST server.

py_binary(
    name = "flask",
    srcs = ["flask.py"],
    deps = [
        "//third_party/py/flask",
        "//third_party/py/sqlalchemy",
        "//util/freefocus",
        "//util/freefocus:sql",
    ],
)
