# FreeFocus REST server.

py_binary(
    name = "server",
    srcs = ["server.py"],
    deps = [
        "//util/freefocus",
        "//util/freefocus:sql",
        "//third_party/py/sqlalchemy",
        "//third_party/py/flask",
    ],
)
