#!/bin/bash
# Shell environment for the project.
# This file is generated by ./configure. Any edits to this file will be
# overwritten the next time ./configure is run.

export PHD="@phd_root@"

if [[ -f "$HOME/.cache/phd/tools/py/venv/phd/bin/activate" ]]; then
  # If there is a virtualenv, use it. Note that even if it does exist, bazel
  # will go ahead and ignore it, so we still need to rely on the system python
  # being the required version.
  . "$HOME/.cache/phd/tools/py/venv/phd/bin/activate"
fi

# Note(github.com/ChrisCummins/phd/issues/55): On macOS, custom LDFLAGS and
# CPPFLAGS are required to pip build MySQLdb:
export LDFLAGS="-L/usr/local/opt/openssl/lib"
export CPPFLAGS="-I/usr/local/opt/openssl/include"

# Increase the timeout on docker image pulls from the default 600s.
# See: https://github.com/bazelbuild/rules_docker
export PULLER_TIMEOUT=3600
