# Scripts and data for machine florence.

py_binary(
    name = "transcode_musiclib",
    srcs = ["transcode_musiclib.py"],
    deps = [
        "//lib/labm8:fs",
        "//lib/labm8:system",
        "//third_party/py/absl",
    ],
)
