# Scripts and data for machine florence.

py_binary(
    name = "transcode_musiclib",
    srcs = ["transcode_musiclib.py"],
    deps = [
        "//labm8:app",
        "//labm8:fs",
        "//labm8:system",
    ],
)
