cc_test(
    name = "algorithm",
    size = "small",
    srcs = [
        "algorithm.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "array",
    size = "small",
    srcs = [
        "array.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "forward_list",
    size = "small",
    srcs = [
        "forward_list.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "list",
    size = "small",
    srcs = [
        "list.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "map",
    size = "small",
    srcs = [
        "map.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "set",
    size = "small",
    srcs = [
        "set.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "stack",
    size = "small",
    srcs = [
        "stack.cc",
        "tests.cc",
        "tests.h",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "type_traits",
    size = "small",
    srcs = [
        "tests.cc",
        "tests.h",
        "type_traits.cc",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "unordered_map",
    size = "small",
    srcs = [
        "tests.cc",
        "tests.h",
        "unordered_map.cc",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)

cc_test(
    name = "vector",
    size = "small",
    srcs = [
        "tests.cc",
        "tests.h",
        "vector.cc",
    ],
    copts = [
        "-Ilab/stl/include",
        "-Isrc/phd/include",
        "-Iexternal/gtest/include",
        "-Iexternal/benchmark/include",
    ],
    deps = [
        "//lab/stl:main",
        "//src/phd:main",
    ],
)
