cc_test(
    name = 'algorithm',
    srcs = [
        'algorithm.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'array',
    srcs = [
        'array.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'forward_list',
    srcs = [
        'forward_list.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'list',
    srcs = [
        'list.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'map',
    srcs = [
        'map.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'set',
    srcs = [
        'set.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'stack',
    srcs = [
        'stack.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'type_traits',
    srcs = [
        'type_traits.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'unordered_map',
    srcs = [
        'unordered_map.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)

cc_test(
    name = 'vector',
    srcs = [
        'vector.cc',
        'tests.cc',
        'tests.h',
    ],
    copts = [
        '-Ilab/stl/include',
        '-Isrc/phd/include',
        '-Iexternal/gtest/include',
        '-Iexternal/benchmark/include',
    ],
    deps = [
        '//lab/stl:main',
        '//src/phd:main',
    ],
    size = 'small',
)
