# Protos for describing 'dpack' data packages.

load("@org_pubref_rules_protobuf//python:rules.bzl", "py_proto_library")

py_proto_library(
    name = "dpack_pb2_py",
    protos = ["dpack.proto"],
    visibility = ["//lib/dpack:__subpackages__"],
)
