# LLVM bytecode datasets.

py_library(
    name = "bytecode_database",
    srcs = ["bytecode_database.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//deeplearning/ml4pl:ml4pl_pb_py",
        "//labm8:pbutil",
        "//labm8:sqlutil",
        "//third_party/py/sqlalchemy",
    ],
)
