# Solutions to <dailycodingproblem.com> challenges.

cc_binary(
    name = "001",
    srcs = ["001.cc"],
)

cc_binary(
    name = "002",
    srcs = ["002.cc"],
)

cc_binary(
    name = "003",
    srcs = ["003.cc"],
)

cc_binary(
    name = "004",
    srcs = ["004.cc"],
)

cc_binary(
    name = "005",
    srcs = ["005.cc"],
)

cc_binary(
    name = "006",
    srcs = ["006.cc"],
)

cc_binary(
    name = "007",
    srcs = ["007.cc"],
)

cc_binary(
    name = "008",
    srcs = ["008.cc"],
)

cc_binary(
    name = "009",
    srcs = ["009.cc"],
)

cc_binary(
    name = "010",
    srcs = ["010.cc"],
)
