# Solutions to <dailycodingproblem.com> challenges.

cc_binary(
    name = "001",
    srcs = ["001.cc"],
)

cc_binary(
    name = "002",
    srcs = ["002.cc"],
)

cc_binary(
    name = "003",
    srcs = ["003.cc"],
)
