# Solutions to <dailycodingproblem.com> challenges.

cc_test(
    name = "001",
    srcs = ["001.cc"],
)

cc_test(
    name = "002",
    srcs = ["002.cc"],
)

cc_test(
    name = "003",
    srcs = ["003.cc"],
)

cc_test(
    name = "004",
    srcs = ["004.cc"],
)

cc_test(
    name = "005",
    srcs = ["005.cc"],
)

cc_test(
    name = "006",
    srcs = ["006.cc"],
)

cc_test(
    name = "007",
    srcs = ["007.cc"],
)

cc_test(
    name = "008",
    srcs = ["008.cc"],
    linkopts = ["-lpthread"],
)

cc_test(
    name = "009",
    srcs = ["009.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

cc_test(
    name = "010",
    srcs = ["010.cc"],
)

cc_test(
    name = "011",
    srcs = ["011.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

py_test(
    name = "012",
    srcs = ["012.py"],
    deps = [
        "//labm8/py:test",
    ],
)

cc_test(
    name = "013",
    srcs = ["013.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

cc_test(
    name = "014",
    srcs = ["014.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

cc_test(
    name = "018",
    srcs = ["018.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

py_test(
    name = "019",
    srcs = ["019.py"],
    deps = [
        "//labm8/py:test",
    ],
)

cc_test(
    name = "064",
    srcs = ["064.cc"],
    deps = [
        "//labm8/cpp:port",
        "//labm8/cpp:test",
    ],
)

cc_test(
    name = "335",
    srcs = ["335.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

cc_test(
    name = "364",
    srcs = ["364.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)

py_test(
    name = "371",
    srcs = ["371.py"],
    deps = [
        "//labm8/py:test",
    ],
)

py_test(
    name = "373",
    srcs = ["373.py"],
    deps = [
        "//labm8/py:test",
    ],
)

cc_test(
    name = "374",
    srcs = ["374.cc"],
    deps = [
        "//labm8/cpp:test",
    ],
)
