load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["file_in_library.go"],
    importpath = "github.com/ChrisCummins/phd/learn/go/first_library",
    visibility = ["//visibility:public"],
)
