# Test logs.

filegroup(
    name = "testlogs",
    srcs = glob([
        "**/test.log",
        "**/test.xml",
    ]),
    visibility = ["//tools/continuous_integration/buildbot/report_generator:__subpackages__"],
)
