cc_binary(
    name = "create_random_graph",
    testonly = 1,
    srcs = ["create_random_graph.cc"],
    deps = [
        "//deeplearning/ml4pl/graphs:graphviz_converter",
        "//deeplearning/ml4pl/graphs:random_graph_builder",
        "//labm8/cpp:app",
        "//labm8/cpp:logging",
    ],
)
