#!/usr/bin/env bash
#
# Eval synthetic kernels. Outputs CSV. Set TABULAR=1 for formatted
# output.
#
set -eu

mktable() {
    set +u
    if [[ -n "$TABULAR" ]]; then
        column -t -s','
    else
        cat
    fi
    set -u
}

# Header
echo "Training, Testing, Features, Platform, Group, Classifier, Accuracy, Speedup, Oracle"

echo
(
    for f in ~/phd/lab/smith/ml/data/a/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), cgo13 features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --test $f | tail -n1
    done
) | mktable
(
    for f in ~/phd/lab/smith/ml/data/b/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), cgo13 features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --test $f | tail -n1
    done
) | mktable

echo
(
    for f in ~/phd/lab/smith/ml/data/a/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), cgo13 features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --test $f | tail -n1
    done
    for f in ~/phd/lab/smith/ml/data/b/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), cgo13 features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --test $f | tail -n1
    done
) | mktable

echo
(
    for f in ~/phd/lab/smith/ml/data/a/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), raw features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --only-raw-features \
              --test $f | tail -n1
    done
    for f in ~/phd/lab/smith/ml/data/b/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), raw features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --only-raw-features \
              --test $f | tail -n1
    done
) | mktable

echo
(
    for f in ~/phd/lab/smith/ml/data/a/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), raw features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --only-raw-features \
              --test $f | tail -n1
    done
    for f in ~/phd/lab/smith/ml/data/b/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), raw features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --only-raw-features \
              --test $f | tail -n1
    done
) | mktable

echo
(
    for f in ~/phd/lab/smith/ml/data/a/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), cgo13+raw features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --with-raw-features \
              --test $f | tail -n1
    done
    for f in ~/phd/lab/smith/ml/data/b/suite/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(suite ⊆ B), cgo13+raw features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --with-raw-features \
              --test $f | tail -n1
    done
) | mktable

echo
(
    for f in ~/phd/lab/smith/ml/data/a/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), cgo13+raw features, Platform A, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/a/synthetics.csv \
              --class NearestNeighbour \
              --with-raw-features \
              --test $f | tail -n1
    done
    for f in ~/phd/lab/smith/ml/data/b/benchmark/*.csv; do
        csv=$(basename $f)
        echo -n "train(S), test(benchmark ⊆ B), cgo13+raw features, Platform B, ${csv%.*}, "
        cgo13 ~/phd/lab/smith/ml/data/b/synthetics.csv \
              --class NearestNeighbour \
              --with-raw-features \
              --test $f | tail -n1
    done
) | mktable
